### ISSUE TITLE
Unable to load DLL 'HBAOPlus-bridge-vvvv.dll'

### ISSUE THREAD

**Issue by mpalenque** [dboleslawski/VVVV.HBAOPlus#5]
Tested on clean b36-b37- b38x86  b38x64
and dx11 from last contribution on site

what could be?
TTY is giving me this : 

00:00:30 ERR : Exception occured in TMPluginWrapperNode.Evaluate
00:00:30 ERR : Unable to load DLL 'HBAOPlus-bridge-vvvv.dll': No se puede encontrar el módulo especificado. (Exception from HRESULT: 0x8007007E)
00:00:30 ERR : Exception caused by node during update :/73/0/202
00:00:30 ERR : Exception node name :HBAO+ (DX11)
00:00:30 ERR : System.DllNotFoundException in HBAOPlus-vvvv: Unable to load DLL 'HBAOPlus-bridge-vvvv.dll': No se puede encontrar el módulo especificado. (Exception from HRESULT: 0x8007007E)

Stacktrace:
   at VVVV.Nodes.DX11.NVHBAOPlus.PluginEntry.InitHBAO(IntPtr device)
   at VVVV.Nodes.DX11.NVHBAOPlus.NVHBAOPlusNode.Update(DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.UpdateNode(DX11Node node)

00:00:30  -  : Stack Trace
00:00:30  -  :    at VVVV.Nodes.DX11.NVHBAOPlus.PluginEntry.InitHBAO(IntPtr device)

**Comment by mpalenque** [comment]
To clarify, I also installed Win 10 SDK
copied core dll to folder
Tried the repo version and the contribution version
